# Hummingbot Deploy Setup Script (PowerShell)
# Este script configura o ambiente de deploy para Hummingbot Deploy

Write-Host "🚀 Hummingbot Deploy Setup" -ForegroundColor Cyan
Write-Host ""

# Solicitar informações do usuário
$CONFIG_PASSWORD = Read-Host "Config password [default: admin]"
if ([string]::IsNullOrWhiteSpace($CONFIG_PASSWORD)) { $CONFIG_PASSWORD = "admin" }

$USERNAME = Read-Host "Dashboard username [default: admin]"
if ([string]::IsNullOrWhiteSpace($USERNAME)) { $USERNAME = "admin" }

$PASSWORD = Read-Host "Dashboard password [default: admin]"
if ([string]::IsNullOrWhiteSpace($PASSWORD)) { $PASSWORD = "admin" }

# Configurações padrão
$BOTS_PATH = (Get-Location).Path
$DEBUG_MODE = "false"
$BROKER_HOST = "emqx"
$BROKER_PORT = "1883"
$BROKER_USERNAME = "admin"
$BROKER_PASSWORD = "public"
$DATABASE_URL = "postgresql+asyncpg://hbot:hummingbot-api@postgres:5432/hummingbot_api"
$CLEANUP_INTERVAL = "300"
$FEED_TIMEOUT = "600"
$AWS_API_KEY = ""
$AWS_SECRET_KEY = ""
$S3_BUCKET = ""
$LOGFIRE_ENV = "prod"
$BANNED_TOKENS = '["NAV","ARS","ETHW","ETHF","NEWT"]'

# Criar arquivo .env
$envContent = @"
# Hummingbot Deploy Configuration
# Generated by setup.ps1

# Dashboard credentials
USERNAME=$USERNAME
PASSWORD=$PASSWORD
CONFIG_PASSWORD=$CONFIG_PASSWORD

# Bot paths
BOTS_PATH=$BOTS_PATH

# Debug settings
DEBUG_MODE=$DEBUG_MODE

# MQTT Broker settings
BROKER_HOST=$BROKER_HOST
BROKER_PORT=$BROKER_PORT
BROKER_USERNAME=$BROKER_USERNAME
BROKER_PASSWORD=$BROKER_PASSWORD

# Database settings
DATABASE_URL=$DATABASE_URL

# Feed and cleanup settings
CLEANUP_INTERVAL=$CLEANUP_INTERVAL
FEED_TIMEOUT=$FEED_TIMEOUT

# AWS S3 settings (optional)
AWS_API_KEY=$AWS_API_KEY
AWS_SECRET_KEY=$AWS_SECRET_KEY
S3_BUCKET=$S3_BUCKET

# Logging
LOGFIRE_ENV=$LOGFIRE_ENV

# Banned tokens
BANNED_TOKENS=$BANNED_TOKENS
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8 -NoNewline

Write-Host ""
Write-Host "✅ Arquivo .env criado com sucesso!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Configuração:" -ForegroundColor Yellow
Write-Host "   Dashboard Username: $USERNAME" -ForegroundColor White
Write-Host "   Dashboard Password: $PASSWORD" -ForegroundColor White
Write-Host "   Config Password: $CONFIG_PASSWORD" -ForegroundColor White
Write-Host ""
Write-Host "🚀 Iniciando serviços com Docker Compose..." -ForegroundColor Cyan

# Verificar se Docker está rodando
$dockerRunning = docker ps 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Docker não está rodando. Inicie o Docker Desktop primeiro." -ForegroundColor Red
    exit 1
}

# Iniciar serviços
docker-compose up -d

Write-Host ""
Write-Host "✅ Serviços iniciados!" -ForegroundColor Green
Write-Host ""
Write-Host "📱 Acesso aos serviços:" -ForegroundColor Yellow
Write-Host "   Dashboard:     http://localhost:8501" -ForegroundColor White
Write-Host "   API Docs:      http://localhost:8000/docs" -ForegroundColor White
Write-Host "   EMQX Broker:   http://localhost:18083 (admin/public)" -ForegroundColor White
Write-Host "   PostgreSQL:    localhost:5432 (hbot/hummingbot-api)" -ForegroundColor White
Write-Host ""
Write-Host "⏳ Aguarde alguns segundos para os serviços iniciarem completamente." -ForegroundColor Cyan
